version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mini_task_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mini_task_mysql
      MYSQL_USER: mini_task_user
      MYSQL_PASSWORD: minipassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mini_task_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: mini_task_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8100:80"
    depends_on:
      - mysql
    networks:
      - mini_task_network

volumes:
  mysql_data:

networks:
  mini_task_network:
    driver: bridge
